[build]
  base = "client"  # Directory where your React app resides
  publish = "client/build"  # Directory where the build files are located
  command = "npm run build"  # Command to build your React app

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
